/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    projects: Project;
    clients: Client;
    jobs: Job;
    'skill-groups': SkillGroup;
    messages: Message;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'skill-groups': SkillGroupsSelect<false> | SkillGroupsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fr' | 'en') | ('fr' | 'en')[];
  globals: {
    site: Site;
    labels: Label;
    home: Home;
    'services-page': ServicesPage;
    'work-page': WorkPage;
    'clients-page': ClientsPage;
    'background-page': BackgroundPage;
    'contact-page': ContactPage;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
    labels: LabelsSelect<false> | LabelsSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    'work-page': WorkPageSelect<false> | WorkPageSelect<true>;
    'clients-page': ClientsPageSelect<false> | ClientsPageSelect<true>;
    'background-page': BackgroundPageSelect<false> | BackgroundPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
  };
  locale: 'fr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describes the image for screen readers. Leave empty for decorative images.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  shortDesc: string;
  longDesc: string;
  deliverables?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  stack?: string[] | null;
  /**
   * Id of the block on the services page.
   */
  anchor: 'web' | 'agents' | 'rag' | 'audit';
  /**
   * Lowest first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  tag: string;
  shortDesc: string;
  longDesc: string;
  /**
   * The alternative text is set on the media itself.
   */
  image: number | Media;
  client?: string | null;
  result?: string | null;
  /**
   * Comma-separated, shown as is.
   */
  stack?: string | null;
  year?: string | null;
  category: 'web' | 'ia';
  /**
   * Lowest first.
   */
  order: number;
  showOnHome?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  /**
   * Not translated.
   */
  name: string;
  logo: number | Media;
  /**
   * Square or compact logos look too big at the default size.
   */
  logoSize: 'default' | 'mid' | 'small';
  sector: string;
  work: string;
  /**
   * Lowest first.
   */
  order: number;
  showOnHome?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  /**
   * Shown as is, e.g. “2014 — now”.
   */
  years: string;
  role: string;
  org: string;
  description: string;
  /**
   * Lowest first.
   */
  order: number;
  showOnHome?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-groups".
 */
export interface SkillGroup {
  id: number;
  title: string;
  /**
   * Names are not translated. The home page lists every group as a single flat list.
   */
  skills: string[];
  /**
   * Lowest first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  email: string;
  message: string;
  locale: 'fr' | 'en';
  /**
   * Salted hash of the IP address, only used to spot repeated senders.
   */
  ipHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'skill-groups';
        value: number | SkillGroup;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  shortDesc?: T;
  longDesc?: T;
  deliverables?:
    | T
    | {
        text?: T;
        id?: T;
      };
  stack?: T;
  anchor?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  tag?: T;
  shortDesc?: T;
  longDesc?: T;
  image?: T;
  client?: T;
  result?: T;
  stack?: T;
  year?: T;
  category?: T;
  order?: T;
  showOnHome?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  logoSize?: T;
  sector?: T;
  work?: T;
  order?: T;
  showOnHome?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  years?: T;
  role?: T;
  org?: T;
  description?: T;
  order?: T;
  showOnHome?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-groups_select".
 */
export interface SkillGroupsSelect<T extends boolean = true> {
  title?: T;
  skills?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  email?: T;
  message?: T;
  locale?: T;
  ipHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  name: string;
  businessName: string;
  jobTitle: string;
  /**
   * Shown after “© <year>” in the footer; the year is added at build time.
   */
  copyrightHolder: string;
  /**
   * Used by the mailto: links, the structured data and the contact form fallback.
   */
  email: string;
  location: string;
  availability?: string | null;
  languages?: string | null;
  address: {
    locality: string;
    region?: string | null;
    country: string;
  };
  socials?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Structured data (schema.org knowsAbout).
   */
  knowsAbout?: string[] | null;
  /**
   * File served by the site, e.g. /assets/og-fr.png (1200×630).
   */
  ogImagePath: string;
  ogImageAlt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "labels".
 */
export interface Label {
  id: number;
  nav: {
    services: string;
    work: string;
    clients: string;
    background: string;
    contact: string;
    home: string;
  };
  a11y: {
    skipLink: string;
    mainNavigation: string;
    language: string;
    menu: string;
    socials: string;
  };
  common: {
    contactButton: string;
    seeAllServices: string;
    seeAllProjects: string;
    seeAllClients: string;
    seeFullBackground: string;
    stack: string;
    deliverables: string;
  };
  work: {
    filter: string;
    filterAll: string;
    filterWeb: string;
    filterAi: string;
    client: string;
    result: string;
  };
  notFound: {
    title: string;
    backHome: string;
  };
  lightbox: {
    open: string;
    close: string;
    dialog: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  seo: {
    title: string;
    description: string;
  };
  hero: {
    title: string;
    subtitle: string;
    primaryCta: string;
    secondaryCta: string;
    aside?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  sections: {
    services: string;
    projects: string;
    clients: string;
    clientsHeading: string;
    background: string;
  };
  closing: {
    title: string;
    target: 'contact' | 'mailto';
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: number;
  seo: {
    title: string;
    description: string;
  };
  head: {
    title: string;
    subtitle?: string | null;
  };
  methodTitle: string;
  process?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  closing: {
    title: string;
    target: 'contact' | 'mailto';
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-page".
 */
export interface WorkPage {
  id: number;
  seo: {
    title: string;
    description: string;
  };
  head: {
    title: string;
    subtitle?: string | null;
  };
  closing: {
    title: string;
    target: 'contact' | 'mailto';
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients-page".
 */
export interface ClientsPage {
  id: number;
  seo: {
    title: string;
    description: string;
  };
  head: {
    title: string;
    subtitle?: string | null;
  };
  /**
   * Use {count} where the number of clients goes.
   */
  countLabel: string;
  closing: {
    title: string;
    target: 'contact' | 'mailto';
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "background-page".
 */
export interface BackgroundPage {
  id: number;
  seo: {
    title: string;
    description: string;
  };
  head: {
    title: string;
    subtitle?: string | null;
  };
  experienceTitle: string;
  stackTitle: string;
  principlesTitle: string;
  principles?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  closing: {
    title: string;
    target: 'contact' | 'mailto';
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  seo: {
    title: string;
    description: string;
  };
  head: {
    title: string;
    subtitle?: string | null;
  };
  formTitle: string;
  form: {
    emailLabel: string;
    messageLabel: string;
    messagePlaceholder: string;
    submitLabel: string;
    privacyNote: string;
    /**
     * Start of the subject when the visitor’s mail client is used as a fallback.
     */
    subjectPrefix: string;
    sentTitle: string;
    sentText: string;
    errorText: string;
  };
  reachTitle: string;
  reach: {
    emailLabel: string;
    profilesLabel: string;
    locationLabel: string;
    languagesLabel: string;
    brief: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  name?: T;
  businessName?: T;
  jobTitle?: T;
  copyrightHolder?: T;
  email?: T;
  location?: T;
  availability?: T;
  languages?: T;
  address?:
    | T
    | {
        locality?: T;
        region?: T;
        country?: T;
      };
  socials?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  knowsAbout?: T;
  ogImagePath?: T;
  ogImageAlt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "labels_select".
 */
export interface LabelsSelect<T extends boolean = true> {
  nav?:
    | T
    | {
        services?: T;
        work?: T;
        clients?: T;
        background?: T;
        contact?: T;
        home?: T;
      };
  a11y?:
    | T
    | {
        skipLink?: T;
        mainNavigation?: T;
        language?: T;
        menu?: T;
        socials?: T;
      };
  common?:
    | T
    | {
        contactButton?: T;
        seeAllServices?: T;
        seeAllProjects?: T;
        seeAllClients?: T;
        seeFullBackground?: T;
        stack?: T;
        deliverables?: T;
      };
  work?:
    | T
    | {
        filter?: T;
        filterAll?: T;
        filterWeb?: T;
        filterAi?: T;
        client?: T;
        result?: T;
      };
  notFound?:
    | T
    | {
        title?: T;
        backHome?: T;
      };
  lightbox?:
    | T
    | {
        open?: T;
        close?: T;
        dialog?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        primaryCta?: T;
        secondaryCta?: T;
        aside?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  sections?:
    | T
    | {
        services?: T;
        projects?: T;
        clients?: T;
        clientsHeading?: T;
        background?: T;
      };
  closing?:
    | T
    | {
        title?: T;
        target?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  head?:
    | T
    | {
        title?: T;
        subtitle?: T;
      };
  methodTitle?: T;
  process?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  closing?:
    | T
    | {
        title?: T;
        target?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-page_select".
 */
export interface WorkPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  head?:
    | T
    | {
        title?: T;
        subtitle?: T;
      };
  closing?:
    | T
    | {
        title?: T;
        target?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients-page_select".
 */
export interface ClientsPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  head?:
    | T
    | {
        title?: T;
        subtitle?: T;
      };
  countLabel?: T;
  closing?:
    | T
    | {
        title?: T;
        target?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "background-page_select".
 */
export interface BackgroundPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  head?:
    | T
    | {
        title?: T;
        subtitle?: T;
      };
  experienceTitle?: T;
  stackTitle?: T;
  principlesTitle?: T;
  principles?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  closing?:
    | T
    | {
        title?: T;
        target?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  head?:
    | T
    | {
        title?: T;
        subtitle?: T;
      };
  formTitle?: T;
  form?:
    | T
    | {
        emailLabel?: T;
        messageLabel?: T;
        messagePlaceholder?: T;
        submitLabel?: T;
        privacyNote?: T;
        subjectPrefix?: T;
        sentTitle?: T;
        sentText?: T;
        errorText?: T;
      };
  reachTitle?: T;
  reach?:
    | T
    | {
        emailLabel?: T;
        profilesLabel?: T;
        locationLabel?: T;
        languagesLabel?: T;
        brief?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}